version: '3.8'

services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-dev
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    environment:
      - PHP_IDE_CONFIG=serverName=php-dev